name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests (if you have tests)
      run: echo "No tests yet"  # Replace with `npm test` if tests exist

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cicd-app:v1.0.1 .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/cicd-app:v1.0.1

    - name: Deploy Docker container
      run: |
        echo "Pulling latest Docker image..."
        docker pull ${{ secrets.DOCKER_USERNAME }}/cicd-app:v1.0.1

        echo "Listing current running containers:"
        docker ps

        echo "Checking for old container using the same image..."
        CONTAINER_ID=$(docker ps -q -f "ancestor=${{ secrets.DOCKER_USERNAME }}/cicd-app:v1.0.1")

        if [ ! -z "$CONTAINER_ID" ]; then
          echo "Stopping and removing container ID: $CONTAINER_ID"
          docker stop $CONTAINER_ID && docker rm $CONTAINER_ID
        else
          echo "No running container found from the same image."
        fi

        echo "Running new container from updated image..."
        docker run -d --name cicd-app -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/cicd-app:v1.0.1
