name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests (if you have tests)
      run: echo "No tests yet"  # Replace with `npm test` if you have tests

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cicd-app .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/cicd-app

    # Deploy container: Stop & Remove old container, then run the new one
    - name: Deploy Docker container
  run: |
    # Pull the latest image
    docker pull ${{ secrets.DOCKER_USERNAME }}/cicd-app

    # Stop and remove any running container based on the image (if exists)
    CONTAINER_ID=$(docker ps -q -f "ancestor=${{ secrets.DOCKER_USERNAME }}/cicd-app")
    if [ ! -z "$CONTAINER_ID" ]; then
      docker stop $CONTAINER_ID && docker rm $CONTAINER_ID
    fi

    # Run the new container
    docker run -d --name cicd-app -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/cicd-app
